config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end
  resources :store

 root :to=> 'store#index', :as=>'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pragprog Books Online Store</title>
	<%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag "scaffold" %>
	<%= stylesheet_link_tag "depot" , :media => "all" %>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
</head>

<body id="store">
	<div id="banner">
		<%= image_tag("logo.png" ) %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	<div id="columns">
		<div id="side">
			

			<a href="http://192.168.16.123">Home</a><br />
			<a href="http://www..../faq">Questions</a><br />
			<a href="http://www..../news">News</a><br />
			<a href="http://www..../contact">Contact</a><br />
			<%= link_to 'New User', new_user_path %>
			<% if session[:user_id] %>
			<br />
			<%= link_to 'Orders',orders_path %><br />
			<%= link_to 'Products', products_path %><br />
			<%= link_to 'Users', users_path	%><br />
			<br />
			<%= button_to 'Logout', logout_path, :method => :delete %>
			<% end %>


			</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>